[project]
name = "djangoStore"
version = "1.0.0"
description = "Django project"
requires-python = ">=3.8"
dependencies = [
    "django>=4.2,<5.0",
    "django-cors-headers>=4.4.0",
    "django-filter>=24.3",
    "django-redis",
    "djangorestframework>=3.14",
    "gunicorn>=21.0",
    "itsdangerous>=2.2.0",
    "pymysql>=1.1.2",
    "qqlogintool>=0.3.0",
    "ronglian-sms-sdk>=1.0",
]

[[tool.uv.index]]
url = "https://pypi.org/simple/"
default = true
