    listen 80;
    
    location / {
        proxy_pass http://frontend:8080;
    }
    
    location /api/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
    }
    
    location /admin/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
    }
    
    location /static/ {
        proxy_pass http://django:8000;
    }
}