server {
    listen 80;
    
    location / {
        proxy_pass http://front_end_pc:8000;
    }
    
    location / {
        proxy_pass http://django_app:8000;
        proxy_set_header Host $host;
    }
    
    location /api/ {
        proxy_pass http://django_app:8000;
        proxy_set_header Host $host;
    }
    
    location /admin/ {
        proxy_pass http://django_app:8000;
        proxy_set_header Host $host;
    }
}